# โครงสร้างควบคุม

โปรแกรมในภาษา Java ประกอบขึ้นจากคำสั่ง (statement) ซึ่งโดยปกติจะทำงานตามลำดับไปจนสิ้นสุดส่วนของโปรแกรม เช่น เริ่มที่ต้นเมทอดไปจนสิ้นสุดเมทอด แต่โดยปกติแล้ว การทำงานใด ๆ ที่มีความซับซ้อนจะไม่ได้ทำตามลำดับขั้นตอนไปตลอด แต่มักจะต้องมีการตัดสินใจ การเลือกทำกรณีเฉพาะที่แตกต่างกัน การทำบางขั้นตอนซ้ำ ๆ การออกจากส่วนของโปรแกรมก่อนจะถึงจุดสิ้นสุด หรือลักษณะอื่น ๆ ที่ทำให้โปรแกรมไม่ทำงานไปตามลำดับปกติ

กลไกที่มาสนับสนุนการเปลี่ยนแปลงลำดับการทำงานให้เป็นไปตามที่เราต้องการนั้นคือโครงสร้างควบคุม (control structure) ซึ่งเป็นรูปแบบคำสั่งที่กำหนดทิศทางการทำงานต่าง ๆ ได้ โครงสร้างควบคุมที่เราจะพิจารณากันในที่นี้คือ ทางเลือก การทำซ้ำ และการเรียกเมทอด

> **หมายเหตุ** โปรแกรมตัวอย่างที่แสดงในบทนี้บางส่วนอาจจะเป็นเพียงส่วนของโปรแกรม การนำไปรันอาจต้องเพิ่มโครงของคลาสและเมทอด `main` ตามความเหมาะสม

## การทำงานตามลำดับ

ในสภาวะปกติที่ไม่มีคำสั่งควบคุมลำดับการทำงานเลย การทำงานของโปรแกรมจะเป็นไปตามลำดับ จากซ้ายไปขวาถ้ามีหลายคำสั่งในบรรทัดเดียวกัน และจากบนลงล่าง เราเรียกลักษณะการทำงานแบบนี้ว่าการควบคุมแบบตามลำดับ (sequential control) ซึ่งเป็นรูปแบบโดยปริยายเมื่อไม่มีการใช้คำสั่งควบคุมใด ๆ

### คำสั่งแบบบล็อก

Java มีโครงสร้างพิเศษที่ทำให้เราสามารถรวมหลาย ๆ คำสั่งไว้ด้วยกันแล้วมองเป็นคำสั่งเดียวได้ เรียกว่าคำสั่งแบบบล็อก (block statement) ซึ่งประกอบด้วยคำสั่งหลาย ๆ คำสั่งครอบด้วยเครื่องหมายวงเล็บปีกกา

In [7]:
public class BlockDemo {
    public static void main(String[] args) {
        int a = 10;
        double b = 5.25;
        
        System.out.println("Outside of the block");
        
        {
            double c = 15.4;
            
            System.out.println("Inside the block");
            System.out.println("... where a + c = " + (a + c));
        }
        
        System.out.println("Outside again");
        System.out.println("... where a + b = " + (a + b));
        System.out.println("... and where there is no c");
    }
}

BlockDemo.main(new String[0]);

Outside of the block
Inside the block
... where a + c = 25.4
Outside again
... where a + b = 15.25
... and where there is no c


การทำงานภายในบล็อกก็ยังคงเป็นลำดับต่อเนื่องจากภายนอกบล็อกตามปกติ แต่จากภายนอกจะมองเสมือนคำสั่งภายในบล็อกรวมกันเป็นคำสั่งเดียว การประกาศตัวแปรใด ๆ ภายในบล็อกจะมีขอบเขตเพียงภายในบล็อก ในตัวอย่างนี้ ส่วนที่อยู่นอกบล็อกจะไม่สามารถอ้างอิงตัวแปร `c` ได้เนื่องจากประกาศอยู่ภายในบล็อก

## การทำงานแบบมีทางเลือก

โครงสร้างควบคุมที่ทำให้เราสามารถเลือกการทำงานได้ตามเงื่อนไขที่ระบุในภาษา Java มีอยู่ 2 แบบ ได้แก่ `if`/`else` และ `switch`

คำสั่ง `if`/`else` จะเลือกทำงานระหว่าง 2 ทางเลือกตามเงื่อนไข ถ้าเงื่อนไขเป็นจริงก็จะทำทางเลือกแรก แต่ถ้าเงื่อนไขไม่จริง ในกรณีที่ไม่มี `else` ก็จะไม่ทำอะไร แต่ทำคำสั่งถัดไปต่อไปเลย ในกรณีที่มี `else` ก็จะทำทางเลือกของ `else` ก่อนจะทำคำสั่งถัดไปต่อไป

รูปแบบวากยสัมพันธ์ของ `if` เป็นดังนี้

```
if (condition)
    true-branch
```

แบบที่มี `else` มีลักษณะดังนี้

```
if (condition)
    true-branch
else
    false-branch
```

_condition_ คือเงื่อนไขที่จะทดสอบ มีค่าเป็นชนิด `boolean` คือเป็นค่า `true` หรือ `false`

_true-branch_ คือคำสั่งที่จะให้ทำถ้าเงื่อนไขเป็นจริง และจะทำ _false-branch_ สำหรับกรณีที่มี `else` และเงื่อนไขเป็นเท็จ คำสั่งที่ให้ทำในแต่ละทางเลือกจะเป็นคำสั่งเดี่ยว ๆ คำสั่งเดียว หรือจะเป็นหลายคำสั่งรวมกันในรูปของคำสั่งแบบบล็อกก็ได้

### รูปแบบของเงื่อนไข

เงื่อนไขที่ใช้กับ `if` จะต้องมีค่าเป็น `true` หรือ `false` หมายความว่าต้องเป็นค่าชนิด `boolean` ซึ่งจะได้จาก

1. ค่าชนิด `boolean` โดยตรง ได้แก่ ค่า `true` และ `false`
2. ตัวแปรชนิด `boolean`
3. ผลจากตัวดำเนินการเปรียบเทียบหรือทดสอบ เช่น `==`, `>=`, `<` หรือ `instanceof`
4. ผลจากตัวดำเนินการตรรกะ เช่น `&&`, `||` หรือ `!`

ตัวดำเนินการเปรียบเทียบมีทั้งหมด 6 แบบ ได้แก่ น้อยกว่า (`<`) น้อยกว่าหรือเท่ากัน (`<=`) มากกว่าหรือเท่ากัน (`>=`) มากกว่า (`>`) เท่ากัน (`==`) และไม่เท่ากัน (`!=`) ส่วนตัวดำเนินการทดสอบมีแบบเดียวคือ `instanceof` ซึ่งใช้ทดสอบความสัมพันธ์ระหว่างอ็อบเจกต์และคลาส

ตัวดำเนินการตรรกะมีทั้งหมด 6 แบบ ได้แก่ นิเสธหรือ not (`!`), and (`&&`), or, (`||`), strict exclusive-or (`^`), strict and (`&`) และ strict or (`|`)

โดยปกติแล้ว ตัวดำเนินการตรรกะที่เราใช้บ่อยคือ `!`, `&&` และ `||` ส่วนอีก 3 ตัวที่เหลือมักจะพบการใช้เป็นการดำเนินการระดับบิตกับข้อมูลชนิดตัวเลขมากกว่า

ตัวดำเนินการตรรกะมีลำดับความสำคัญต่ำกว่าตัวดำเนินการเปรียบเทียบ เพราะฉะนั้นถ้าอยู่ร่วมกันในนิพจน์เดียวกัน ตัวดำเนินการเปรียบเทียบจะถูกทำก่อน

ตัวอย่างต่อไปนี้แสดงการใช้งาน `if` และเงื่อนไขในรูปแบบต่าง ๆ

In [9]:
int x = 10;
int y = 20;
boolean b = true;
boolean c = b && x < y; // true

if (x < y - 10)
    System.out.println("First case is true");

if (c) {
    // Using block statement here
    System.out.println("Second case is true");
} else {
    // Also block statement here
    System.out.println("Second case if false");
}

// Nested if's, all using block statements
if (x + 1 > y) {
    System.out.println("Third case is true");
} else if (x + 5 > y && y < 30) {
    System.out.println("Fourth case is true");
} else if (x + 10 > y && y < 40) {
    System.out.println("Fifth case is true");
} else {
    System.out.println("Nothing is true");
}

Second case is true
Nothing is true


### นิพจน์เงื่อนไข

เราสามารถใช้ทางเลือกในนิพจน์ได้ในรูปของนิพจน์เงื่อนไข ซึ่งมีรูปแบบเป็น `condition ? value1 : value2` ซึ่งจะให้ผลลัพธ์เป็นค่าของ _value1_ ถ้า _condition_ เป็นจริงหรือ _value2_ ถ้า _condition_ เป็นเท็จ

In [10]:
int x = -10;
int y = x < 0 ? -x : x;

System.out.println(y);

10


ในตัวอย่างนี้ค่าของ `y` จะขึ้นอยู่กับเงื่อนไข `x < 0` ซึ่งถ้าจริง `y` ก็จะเท่ากับ `-x` และถ้าไม่จริง `y` ก็จะเท่ากับ `x` ในกรณีนี้ค่าของ `x` เป็นลบ จึงเข้าเงื่อนไขที่เป็นค่า `-x` ค่าของ `y` จึงได้เป็น 10

### คำสั่งทางเลือกแบบหลายทาง

ในบางกรณีเราต้องการเลือกทางเลือกจากค่าของตัวแปรหรือค่าผลลัพธ์ของนิพจน์ โดยผลลัพธ์แต่ละค่าจะเป็นทางเลือกที่ต่างกัน และมีหลายทางเลือก ในกรณีนี่เราอาจจะใช้คำสั่ง `switch` ในการจัดการ

คำสั่ง `switch` จะอยู่ในรูป

```
switch (expression) {
    case constant1: branch1
    case constant2: branch2
    ...
    default: branchn
}
```

ส่วนของ _expression_ เป็นค่าที่ `switch` จะพิจารณาเพื่อเลือกทางเลือก โดยต้องมีชนิดเป็น `int`, `short`, `char`, `byte`, `enum`, `String` หรือเป็นคลาสหีบห่อ (wrapper class) ของ `int`, `short`, `char` และ `byte`

`switch` จะเทียบค่าของ _expression_ กับค่า _constant_ ของแต่ละ `case` ว่าตรงกับอันไหน แล้วก็จะเริ่มทำคำสั่งตาม _branch_ ที่ตรงกับ `case` นั้น โดยจะทำไปเรื่อย ๆ จนกว่าจะสิ้นสุดคำสั่ง `switch` หรือจนกว่าจะเจอคำสั่ง `break`

ในกรณีที่ค่าของ _expression_ ไม่ตรงกับ `case` ใดเลย จะทำคำสั่งที่กำหนดที่ `default` ยกเว้นจะไม่ได้กำหนดส่วนของ `default` เอาไว้

ตัวอย่างต่อไปนี้เป็นการใช้ `switch` เบื้องต้น

In [11]:
int day = 4;
String dayName;

switch (day) {
    case 1:
        dayName = "Sunday";
        break;
    case 2:
        dayName = "Monday";
        break;
    case 3:
        dayName = "Tuesday";
        break;
    case 4:
        dayName = "Wednesday";
        break;
    case 5:
        dayName = "Thursday";
        break;
    case 6:
        dayName = "Friday";
        break;
    case 7:
        dayName = "Saturday";
        break;
    default:
        dayName = "No such day";
}

System.out.println(dayName);

Wednesday


จากตัวอย่างนี้ ค่าของ `day` คือ 4 ซึ่งจะตรงกับ `case` ที่กำหนดให้ `dayName` มีค่าเป็น `"Wednesday"` แล้วก็ `break` เลย

ในบางครั้งเราอาจไม่ต้องการ `break` ในบาง `case` เพื่อให้ทำงานต่อไปยัง `case` ต่อไปเลยโดยไม่ออกจาก `switch` ลักษณะแบบนี้เรียกว่า fall through คือปล่อยให้ไหลต่อไป ลองดูตัวอย่างต่อไปนี้

In [27]:
Random dice = new Random();

String prizes = "You've got ";

switch (dice.nextInt(6) + 1) {
    case 1:
        prizes += "a teddy bear.";
        break;
    case 2:
        prizes += "a model robot, ";
    case 3:
        prizes += "a board game, ";
    case 4: case 5:
        prizes += "a lollipop, ";
    case 6:
        prizes += "a fancy mask, ";
    default:
        prizes += "and a lot of fun.";
}

System.out.println(prizes);

You've got a board game, a lollipop, a fancy mask, and a lot of fun.


ตัวอย่างนี้เป็นการทอดลูกเต๋าชิงรางวัล โดยสุ่มค่า 1-6 ด้วยเมทอด `nextInt` (ซึ่งจะได้ค่าในช่วง 0-5 จึงบวกเพิ่มอีก 1) แล้วนำค่าที่สุ่มได้ไปกำหนดรางวัลที่ได้

ในตัวอย่างเราจะเห็นว่า `case 1` จะให้ teddy bear แล้ว `break` เลย แต่ตั้งแต่ `case 2` เป็นต้นไปจะไม่มีการ `break` นอกจากนี้ `case 4` และ `case 5` ยังอยู่รวมกัน ซึ่งหมายความว่าถ้าได้ค่า 4 หรือ 5 ก็จะมาตกกรณีเดียวกัน

ในการรันตัวอย่าง พบว่าทอดลูกเต๋าได้ค่า 3 สตริง `prizes` จึงได้ต่อข้อความมาตั้งแต่ `"a board game, "` ของ `case 3` ไหลต่อเนื่องไปยัง `"a lollipop, "` ของ `case 4` และ `case 5` ไปถึง `"a fancy mask, "` ของ `case 6` และไปจบที่ `"and a lot of fun."` ของ `default` เนื่องจากไม่มีการ `break` เลย

กรณีตัวอย่างนี้แสดงให้เห็นการใช้งาน `switch` ในการสะสมค่าต่อเนื่องตั้งแต่กรณีที่ค่าตรงกันไปจนจบ ซึ่งในการใช้งานจริงอาจพบกรณีลักษณะนี้อยู่บ้าง

> **หมายเหตุ** การใช้ `Random` เพื่อสุ่มค่าจะต้องมีการ `import java.util.Random` ก่อน

## การวนซ้ำ

คำสั่งสำหรับวนซ้ำในภาษา Java มีอยู่ 3 รูปแบบด้วยกัน ได้แก่ `while`, `do` ... `while` และ `for` โดย 2 แบบแรกนิยมใช้กับการวนซ้ำตามเงื่อนไข ส่วนแบบหลังนิยมใช้กับการวนซ้ำแบบรู้จำนวนรอบล่วงหน้า ทั้งนี้ ในความเป็นจริงแล้วคำสั่งวนซ้ำทั้ง 3 แบบสามารถใช้แทนกันได้ทั้งหมด

### คำสั่ง while

คำสั่ง `while` หรือลูป (loop) `while` ใช้สำหรับการวนซ้ำโดยพิจารณาตามเงื่อนไข ถ้าเงื่อนไขที่กำหนดเป็นจริงก็ทำซ้ำต่อไปแล้วกลับมาพิจารณาเงื่อนไขใหม่ เมื่อใดที่เงื่อนไขไม่จริงก็จะสิ้นสุดการทำงาน

รูปแบบของคำสั่ง `while` เป็นดังนี้

```
while (condition)
    body
```

_condition_ คือเงื่อนไขที่พิจารณาในการวนซ้ำ โดยจะทำส่วนของ _body_ ตราบเท่าที่เงื่อนไขยังเป็นจริงอยู่ ดังตัวอย่างนี้

In [33]:
int x = 10;
int y = 5;
int sum = 0;

while (x > y) {
    sum += x + y;
    x--;
    y++;
}

System.out.println("Total: " + sum);

Total: 45


ลูปนี้จะทำงานไปเรื่อย ๆ ตราบเท่าที่ค่าของ `x` ยังมากกว่า `y` โดยในแต่ละรอบจะลดค่าของ `x` และเพิ่มค่าของ `y` ด้วย

ในกรณีที่เงื่อนไขไม่เป็นจริงตั้งแต่แรก ลูป `while` จะไม่ทำงานเลย

#### ตัวดำเนินการเพิ่มค่าและลดค่า

ตัวดำเนินการ `++` และ `--` ที่เห็นในตัวอย่างคือตัวดำเนินการเพิ่มค่าและลดค่าซึ่งใช้ได้กับทั้งตัวแปรชนิดจำนวนเต็มและทศนิยม `++` คือการเพิ่มค่าไปอีก 1 ค่าให้กับตัวแปรนั้น และ `--` คือการลดค่าลงไป 1 ค่า เราสามารถใช้ตัวดำเนินการนี้ร่วมกับตัวแปรเป็นส่วนหนึ่งของนิพจน์อื่น ๆ ได้

ตัวดำเนินการ `++` และ `--` มีลักษณะการใช้งาน 2 แบบ คือการเพิ่ม/ลดค่าก่อน และการเพิ่ม/ลดค่าทีหลัง แบบแรกเราจะใช้ตัวดำเนินการนี้หน้าชื่อตัวแปร ตัวแปรจะเปลี่ยนค่าทันที แต่แบบที่สองเราจะใช้ตัวดำเนินการนี้หลังชื่อตัวแปร ค่าเดิมของตัวแปรจะถูกนำไปใช้ในนิพจน์ ตัวแปรจะเปลี่ยนค่าทีหลัง

ลองดูตัวอย่างต่อไปนี้

In [30]:
int n = 5;
int m = ++n;
double x = 2.5;
double y = x++;

System.out.printf("n = %d, m = %d, x = %.1f, y = %.1f%n", n, m, x, y);

y = n++ + --m + x--;

System.out.printf("n = %d, m = %d, x = %.1f, y = %.1f%n", n, m, x, y);

n = 6, m = 6, x = 3.5, y = 2.5
n = 7, m = 5, x = 2.5, y = 14.5


ค่าของ `m` ถูกกำหนดให้เท่ากับ `++n` ซึ่งก็คือเพิ่มค่าให้กับ `n` เป็น 6 ก่อนแล้วจึงกำหนดให้กับ `m` ค่าของ `m` จึงเป็น 6 เช่นกัน ในทางกลับกัน ค่าของ `y` ถูกกำหนดให้เท่ากับ `x++` ซึ่งจะนำค่าของ `x` เดิมคือ 2.5 ไปกำหนดให้กับ `y` ก่อนแล้วจึงเพิ่มค่าให้กับ `x` เป็น 3.5

อีกส่วนหนึ่งคือ `y = n++ + --m + x--` ซึ่งจะมีการเพิ่มค่าให้ `n` และลดค่าของ `m` และ `x` แต่จะใช้ค่าของ `n` และ `x` ก่อนการเปลี่ยนค่าในการคำนวณค่าที่จะกำหนดให้ `y`

บ่อยครั้งที่เรามักจะใช้ตัวดำเนินการ `++` และ `--` เพื่อเพิ่มหรือลดค่าอย่างเดียวโดยไม่ได้นำค่าไปใช้ในนิพจน์อื่นหรือไปกำหนดให้กับตัวแปรอื่นต่อ เช่น ในตัวอย่าง `while` ที่เราใช้ `x--` และ `y++` โดด ๆ โดยไม่ได้นำค่าไปกำหนดให้ตัวแปรอื่นต่อ การใช้ในลักษณะนี้เราจะใช้ตัวดำเนินการก่อนหรือหลังชื่อตัวแปรก็ได้ผลลัพธ์เหมือนกัน

#### ตัวดำเนินการรวมค่า

อีกตัวดำเนินการหนึ่งที่เราเห็นในตัวอย่าง `while` คือ `+=` ซึ่งเราสามารถเรียกได้ว่าเป็นตัวดำเนินการรวมค่า การเขียนว่า `x += n` เทียบเท่าได้กับการเขียนว่า `x = x + n` คือการบวกค่ากับตัวแปรหนึ่งแล้วกำหนดค่านั้นคืนให้กับตัวแปรนั้น มองอีกอย่างได้ว่าเป็นการเอาค่าทางฝั่งขวาของตัวดำเนินการไปเพิ่มให้กับตัวแปรทางฝั่งซ้ายของตัวดำเนินการนั่นเอง ในกรณีของตัวอย่าง `sum += x + y` ก็เหมือนกับการเขียนว่า `sum = sum + (x + y)` ซึ่งก็คือการเอาค่าของ `x + y` ไปเพิ่มให้กับ `sum`

นอกจาก `+=` แล้วยังมีตัวดำเนินการในลักษณะเดียวกันตัวอื่นด้วย ได้แก่ `-=`, `*=`, `/=`, `%=`, `&=`, `|=` และ `^=`

### คำสั่ง do ... while

ลูปที่วนซ้ำตามเงื่อนไขอีกแบบคือลูป `do` ... `while` ซึ่งมีรูปแบบดังนี้

```
do
    body
while (condition);
```

การทำงานของ `do` ... `while` จะต่างจาก `while` ตรงที่การทำงานในส่วนของ _body_ จะเกิดขึ้นก่อนการตรวจสอบ _condition_ ซึ่งหมายความว่าไม่ว่าเงื่อนไขจะเป็นอย่างไร `do` ... `while` จะต้องทำส่วนของ _body_ อย่างน้อย 1 รอบก่อน

หลังจากรอบแรกแล้ว พฤติกรรมของ `do` ... `while` จะไม่ต่างจาก `while`

ตัวอย่างหนึ่งที่เราจะพบการใช้ `do` ... `while` ได้บ่อยคือการรับข้อมูลจากผู้ใช้ เราจะรับค่ามาก่อนแล้วค่อยตรวจสอบว่าค่าที่รับมาถูกต้องหรือไม่ ถ้าไม่ถูกต้องก็กลับไปรับใหม่จนกว่าจะถูกต้อง ดังตัวอย่างนี้

In [36]:
import java.util.Scanner;
import java.util.Random;

public class DoWhileDemo {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        Random random = new Random();
        int secretValue = random.nextInt(9) + 1;
        int guess;
        
        do {
            System.out.print("Enter a number between 1 to 9: ");
            guess = input.nextInt();
            if (guess < secretValue) {
                System.out.println("Too low!");
            } else if (guess > secretValue) {
                System.out.println("Too high!");
            }
        } while (guess != secretValue);
        
        System.out.println("You've got it!");
    }
}

โปรแกรมนี้จะสุ่มค่าระหว่าง 1-9 แล้วให้ผู้ใช้ทายเลข โดยจะให้ทายซ้ำไปเรื่อย ๆ จนกว่าจะทายถูก ถ้าทายไม่ถูกก็จะแจ้งว่าค่าที่ทายสูงไปหรือต่ำไป เราใช้ `do` ... `while` เพราะเราต้องการรับค่าจากผู้ใช้ก่อนแล้วจึงตรวจสอบค่า

ตัวอย่างผลการรันเป็นดังนี้

```
Enter a number between 1 to 9: 5
Too low!
Enter a number between 1 to 9: 7
Too high!
Enter a number between 1 to 9: 6
You've got it!
```

### คำสั่ง for

คำสั่งวนซ้ำตัวสุดท้ายคือคำสั่ง `for` ซึ่งมีรูปแบบดังนี้

```
for (initialization; condition; step)
    body
```

โครงสร้างของคำสั่ง `for` จะมีลำดับการทำงานเป็นดังนี้

1. ทำส่วน _initialization_
2. ทดสอบเงื่อนไขในส่วน _condition_
    - ถ้าเงื่อนไขเป็นจริงให้ทำต่อข้อ 3
    - ถ้าเงื่อนไขเป็นเท็จให้จบการทำงานของคำสั่ง `for`
3. ทำส่วน _body_
4. ทำส่วน _step_
5. กลับไปข้อ 2

จากลำดับนี้จะเห็นได้ว่าส่วน _initialization_ จะทำเพียงครั้งเดียวในตอนเริ่มต้น ส่วนนี้เราจะใช้ในการกำหนดค่าตั้งต้นที่จำเป็นสำหรับการทำซ้ำซึ่งมักจะเป็นการประกาศและกำหนดค่าตั้งต้นให้กับตัวแปรที่ใช้นับจำนวนรอบของการวนซ้ำ แต่ไม่จำเป็นต้องเป็นแบบนั้นเสมอไป

ก่อนการวนซ้ำแต่ละรอบจะมีการทดสอบ _condition_ ซึ่งถ้าเป็นจริงก็จะไปทำส่วน _body_ ซึ่งเป็นโค้ดหลักที่ต้องการให้วนซ้ำ แล้วจึงทำส่วนของ _step_ ซึ่งมักจะเป็นคำสั่งเปลี่ยนค่าของตัวแปรที่ใช้นับรอบ แล้วจึงกลับไปตรวจสอบ _condition_ ใหม่ ดังตัวอย่างนี้

In [38]:
int sum = 0;

for (int i = 0; i < 5; i++) {
    System.out.printf("Adding %d%n", i + 1);
    sum += i + 1;
}

System.out.println("Sum = " + sum);

Adding 1
Adding 2
Adding 3
Adding 4
Adding 5
Sum = 15


ลูป `for` จะเริ่มต้นโดยการประกาศตัวแปร `i` และกำหนดค่าให้เท่ากับ 0 และทุกรอบจะมีการตรวจสอบค่าของ `i` ว่ายังน้อยกว่า 5 อยู่ และทำส่วนของ _body_ คือการแสดงข้อความและบวกค่าตัวนับให้กับตัวแปร `sum` แล้วจึงทำส่วนของ _step_ ซึ่งก็คือการเพิ่มค่าให้กับตัวนับซึ่งก็คือตัวแปร `i` นั่นเอง ส่วน _step_ จึงถือเป็นส่วนที่มีความจำเป็นมากในการทำให้การวนซ้ำมีการเดินหน้าไปถึงจุดสิ้นสุด

ถ้าเราลองพิจารณากันอย่างละเอียดจะพบว่าเราสามารถใช้คำสั่ง `while` แทนคำสั่ง `for` ได้เช่นกัน โดยถ้าต้องการเลียนแบบการทำงานทุกอย่างของ `for` เราสามารถเขียนเป็นคำสั่ง `while` ได้ในรูปนี้

```
initialization
while (condition) {
    body
    step
}
```

ซึ่งถ้าใช้กับโปรแกรมตัวอย่างข้างต้นก็จะได้เป็นดังนี้

In [39]:
int sum = 0;
int i = 0;

while (i < 5) {
    System.out.printf("Adding %d%n", i + 1);
    sum += i + 1;
    i++;
}

System.out.println("Sum = " + sum);

Adding 1
Adding 2
Adding 3
Adding 4
Adding 5
Sum = 15


ข้อแตกต่างของคำสั่ง `for` กับการใช้คำสั่ง `while` แทนในรูปแบบนี้ นอกจากเรื่องความกระชับแล้ว ยังมีความแตกต่างในรายละเอียดเล็กน้อยอีกประเด็น ได้แก่ ขอบเขตของตัวแปรที่ประกาศในส่วน _initialization_ ซึ่งในกรณีของ `for` จะมีขอบเขตแค่ภายในลูป `for` เท่านั้น แต่ในกรณีของ `while` ตัวแปรที่ประกาศขึ้นจะมีขอบเขตในระดับเดียวกับบล็อกที่ครอบคำสั่ง `while` นั้นอยู่ ซึ่งถ้าเป็นเมทอดก็จะมีขอบเขตเป็นทั้งเมทอดนั้น

เนื่องจากในความเป็นจริงแล้วทั้ง `for` และ `while` ก็มีลักษณะที่ทดแทนกันได้ เราจึงสามารถใช้ `for` แทน `while` และใช้กับการวนซ้ำที่มีเงื่อนไขซับซ้อนได้เช่นกัน แต่ในทางปฏิบัติแล้วเราจะนิยมใช้ `for` ในการวนซ้ำที่มีจำนวนรอบแน่นอนเป็นส่วนใหญ่ และใช้ `while` หรือ `do` ... `while` สำหรับกรณีอื่น ๆ

> **หมายเหตุ** ยังมีรูปแบบของคำสั่ง `for` อีกรูปแบบหนึ่งซึ่งใช้กับข้อมูลชนิด collection ซึ่งจะกล่าวถึงในบทต่อไป

### คำสั่ง break

ในการวนซ้ำ บางกรณีเราต้องการยุติการวนซ้ำก่อนที่จะไปถึงการตรวจสอบเงื่อนไขรอบต่อไป ในกรณีนี้เราสามารถใช้คำสั่ง `break` เพื่อยุติการทำงานของลูปได้

พิจารณาตัวอย่างต่อไปนี้

In [42]:
int start = 10000;
int end = 20000;
int step = 7;
int divider = 17;
int stepCount = 0;
int i;

for (i = start; i <= end; i += step) {
    if (i % divider == 0)
        break;
    
    stepCount++;
}

System.out.printf("Found %d in %d steps.%n", i, stepCount);

Found 10098 in 14 steps.


ตัวอย่างนี้เราต้องการหาค่าที่สามารถหารด้วย 17 ลงตัวจากชุดตัวเลขที่เริ่มต้นที่ 10,000 และเพิ่มทีละ 7 ไปจนถึง 20,000

ลูป `for` ในที่นี้จะเป็นการนับตามปกติโดยเพิ่มค่าของ `i` รอบละ 7 แต่ภายในลูปเรามีการตรวจสอบเงื่อนไขเพิ่มเติมว่าค่าของ `i` หาร 17 ลงตัวหรือไม่ ถ้าลงตัวถือว่าเราพบค่าแล้ว ไม่ต้องวนซ้ำต่อ จึง `break` ออกมาจากลูป

คำสั่ง `break` มักจะใช้ร่วมกับคำสั่ง `if` เพื่อตรวจสอบเงื่อนไขในการสิ้นสุดการวนซ้ำเพิ่มเติมก่อนสั่งยุติการวนซ้ำ

### คำสั่ง continue

นอกเหนือจากการยุติการทำงานของลูปด้วยคำสั่ง `break` แล้ว เรายังสามารถควบคุมการทำงานภายในลูปได้อีกลักษณะหนึ่ง คือการสั่งให้ขึ้นรอบการวนซ้ำรอบต่อไปทันทีโดยไม่ทำคำสั่งภายในลูปส่วนที่เหลือ การขึ้นรอบต่อไปก็จะมีการตรวจสอบเงื่อนไขก่อนการทำซ้ำตามปกติ

พิจารณาตัวอย่างต่อไปนี้

In [43]:
// Sum of all except those that are divisible by both 6 and 9
int sum = 0;

for (int i = 1; i <= 100; i++) {
    if (i % 6 == 0 && i % 9 == 0)
        continue;
    
    sum += i;
}

System.out.println("Sum = " + sum);

Sum = 4780


ตัวอย่างนี้เป็นการหาผลรวมของจำนวนเต็มจาก 1-100 โดยยกเว้นตัวเลขที่ทั้ง 6 และ 9 สามารถหารลงตัว เราตรวจสอบเงื่อนไขการหารลงตัวนี้แล้วสั่งให้ขึ้นรอบต่อไปเลยโดยไม่เอาค่ามารวมกับ `sum` ถ้าเลขนั้นหารได้ลงตัว

## เมทอดของคลาส

เมทอดของคลาส (class method) หรือเมทอดสถิต (static method) คือเมทอดที่ประกาศขึ้นโดยมีการระบุตัวกำหนด `static` ซึ่งที่ผ่านมาเราจะเห็นได้ในเมทอด `main`

เมทอดคือโครงสร้างที่รวมคำสั่งจำนวนหนึ่งเอาไว้ด้วยกันเป็นชุด แล้วตั้งชื่อขึ้นมาใหม่เสมือนเป็นคำสั่งใหม่ เปรียบเทียบกับภาษาอื่นอาจจะเปรียบเทียบได้กับฟังก์ชัน แต่ข้อแตกต่างจากฟังก์ชันก็คือ ฟังก์ชันจะเป็นอิสระ แต่เมทอดจะผูกติดอยู่กับคลาสหรืออ็อบเจกต์ ซึ่งหมายความว่าไม่สามารถเรียกใช้โดด ๆ ได้ ต้องเรียกใช้ผ่านคลาสหรือผ่านอ็อบเจกต์ที่ผูกติดอยู่

เมทอดของคลาสเป็นเมทอดที่ถูกผูกติดกับคลาส การเรียกใช้ต้องเรียกผ่านคลาสหรือผ่านอ็อบเจกต์ของคลาสนั้น ยกเว้นจะเป็นการเรียกภายในคลาสเดียวกัน ซึ่งไม่ต้องระบุคลาสอีก

รูปแบบการประกาศเมทอดของคลาสเบื้องต้นเป็นดังนี้

```
access-modifier static return-type methodName(parameter-list)
    method-body
```

- _access-modifiers_ เป็นตัวกำหนดการเข้าถึงไม่เกินหนึ่งตัวระหว่าง `private` กับ `public` หรือไม่ระบุก็ได้ ในที่นี้เราจะใช้ `public` ซึ่งหมายถึงเรียกใช้ได้จากทุกที่ไปก่อน
- _return-type_ เป็นตัวระบุชนิดของข้อมูลที่จะส่งกลับจากเมทอด โดยที่ `void` จะหมายถึงเมทอดนี้ไม่ส่งค่ากลับ
- _parameter-list_ เป็นรายการพารามิเตอร์ที่เมทอดนี้จะรับ
- _method-body_ เป็นตัวโค้ดของเมทอดในรูปของบล็อก

### คำสั่ง return

เมทอดสามารถที่จะคืนค่าผลลัพธ์กลับไปยังผู้เรียกได้ ชนิดของข้อมูลที่คืนค่าจะระบุที่ _return-type_ ถ้า _return-type_ ไม่ใช่ `void` ในตัวโค้ดของเมทอดจะต้องมีคำสั่ง `return` เพื่อคืนค่ากลับ เมื่อพบคำสั่ง `return` เมทอดจะสิ้นสุดการทำงานพร้อมกับส่งค่าที่ระบุในคำสั่ง `return` กลับเป็นผลลัพธ์

ในกรณีที่ระบุ _return-type_ เป็น `void` ซึ่งหมายความว่าเมทอดจะไม่มีการคืนค่ากลับ เมทอดนี้จะมีคำสั่ง `return` หรือไม่มีก็ได้ ถ้ามีก็จะเป็นคำสั่ง `return` แบบไม่ระบุค่า แต่ถ้าไม่มี เมทอดก็จะทำงานจนถึงคำสั่งสุดท้ายในตัวเมทอดแล้วจึงคืนการทำงานกลับไปยังผู้เรียก

ตัวอย่างนี้แสดงการประกาศและใช้เมทอดของคลาส

In [49]:
public class StaticMethodDemo {
    public static int abs(int value) {
        if (value < 0) {
            return -value;
        } else {
            return value;
        }
    }
    
    public static void printGreeting(String name, String message) {
        System.out.printf("Hello, my name is %s.%n", name);
        System.out.printf("Do you know that %s?%n", message);
    }
    
    public static void main(String[] args) {
        int value = -17;
        
        String message = String.format("absolute of %d is %d", value, abs(value));
        
        printGreeting("John", message);
        
        StaticMethodDemo.printGreeting("Jim", "I like sushi");
    }
}

StaticMethodDemo.main(new String[0]);

Hello, my name is John.
Do you know that absolute of -17 is 17?
Hello, my name is Jim.
Do you know that I like sushi?


เมทอด `abs` รับพารามิเตอร์ 1 ตัว และคืนค่ากลับเป็นชนิด `int` ในขณะที่เมทอด `printGreeting` รับพารามิเตอร์ 2 ตัว และไม่คืนค่ากลับ จึงไม่ต้องมีคำสั่ง `return` ในตัวเมทอด

ในเมทอด `main` มีการเรียกใช้เมทอด `printGreeting` 2 ครั้ง ครั้งแรกเรียกชื่อตรง ๆ ครั้งที่สองเรียกผ่านชื่อคลาส ในกรณีที่เมทอดที่เรียกกับเมทอดที่ถูกเรียกอยู่ในคลาสเดียวกัน เราไม่จำเป็นต้องระบุชื่อคลาส แต่ถ้าอยู่ต่างคลาสกัน เราต้องระบุชื่อคลาสด้วยเสมอ

### เมทอด main

เมทอด `main` เป็นเมทอดของคลาสที่เราใช้มาตั้งแต่ต้น เมทอดนี้มีความสำคัญเป็นพิเศษเนื่องจากโปรแกรมจะเริ่มต้นทำงานที่เมทอดนี้ เมทอด `main` จึงเป็นเสมือนตัวตั้งต้นที่ต้องจัดเตรียมสภาวะการทำงานของโปรแกรมให้พร้อมแล้วดำเนินการต่อไป

เมทอด `main` จะเป็นต้องเป็นเมทอดของคลาสซึ่งประกาศด้วยตัวกำหนด `static` เพราะเมทอดของคลาสสามารถเรียกใช้ได้เลยโดยไม่ต้องมีอ็อบเจกต์มาอ้างอิง ขณะที่โปรแกรมเริ่มทำงานระบบจะไม่มีอ็อบเจกต์ใด ๆ อยู่ ดังนั้นเมทอดแรกที่จะเรียกได้ต้องสามารถเรียกได้โดยไม่ต้องอ้างอิงอ็อบเจกต์ เมทอด `main` จึงต้องมีสถานะเป็นเมทอดของคลาส

`main` จะรับพารามิเตอร์เป็นอาร์เรย์ของสตริง ซึ่งเราสามารถส่งเข้ามาให้ได้โดยการกำหนดตอนที่สั่งรันโปรแกรม เช่น กำหนดจาก Command Prompt หรือ Terminal แต่ในวิชานี้เราไม่ได้ใช้คุณสมบัตินั้น จึงไม่กล่าวถึงในที่นี้

ในบทเรื่องคลาสและอ็อบเจกต์ เราจะศึกษาเมทอดอีกประเภท เรียกว่าเมทอดของอินสแตนซ์ (instance method) ซึ่งผูกติดกับอ็อบเจกต์ ไม่สามารถเรียกใช้ผ่านคลาสได้ ต้องเรียกผ่านอ็อบเจกต์เท่านั้น

### ขอบเขตของตัวแปร

ขอบเขต (scope) ของตัวแปรหมายถึงส่วนของโปรแกรมที่สามารถมองเห็นและอ้างอิงตัวแปรเหล่านั้นได้ ตัวแปรที่ประกาศขึ้นในบล็อกใด ๆ จะมีขอบเขตตั้งแต่จุดที่ประกาศไปจนถึงจุดสิ้นสุดบล็อกนั้น ๆ ภายในบล็อกจะไม่สามารถประกาศตัวแปรชื่อซ้ำกันได้

ตัวแปรที่ประกาศเป็นพารามิเตอร์ของเมทอดหรือคอนสตรักเตอร์จะมีขอบเขตทั้งเมทอดหรือคอนสตรักเตอร์นั้น ๆ

ตัวแปรที่ประกาศในส่วนกำหนดค่าตั้งต้นของคำสั่ง `for` จะมีขอบเขตตลอดทั้งคำสั่ง `for` นั้น

ตัวแปรที่ประกาศกับคลาส (ตัวแปรของคลาสและตัวแปรของอินสแตนซ์) จะมีขอบเขตตลอดทั้งคลาส

### การบดบัง

โดยปกติแล้ว เราไม่สามารถประกาศตัวแปรชื่อซ้ำกันภายในบล็อกได้ แม้ว่าตัวแปรหนึ่งจะประกาศที่บล็อกที่ครอบอยู่หรือเป็นพารามิเตอร์และอีกตัวประกาศในบล็อกที่ซ้อนอยู่ด้านในก็ไม่สามารถทำได้ แต่มีข้อยกเว้นอยู่กรณีหนึ่ง คือการที่ตัวแปรตัวหนึ่งประกาศในส่วนของคลาส และอีกตัวหนึ่งประกาศในส่วนของพารามิเตอร์ของเมทอดหรือภายในเมทอด

การประกาศแบบนี้สามารถทำได้ แต่จะทำให้เกิดการบดบัง (shadowing) ขึ้น ซึ่งหมายความว่าเราจะไม่สามารถอ้างอิงถึงตัวแปรของคลาสหรืออ็อบเจกต์ตรง ๆ ในเมทอดนั้นได้ เนื่องจากถูกตัวแปรภายในบดบังอยู่

In [4]:
public class ScopeDemo {
    private static double x = 1.5;
    
    public static void shadowedByParameter(double x) {
        System.out.printf("In shadowedByParameter: parameter x = %.1f%n", x);
    }
    
    public static void shadowedByLocalVariable() {
        double x = 2.5;

        System.out.printf("In shadowedByLocalVariable: local varaible x = %.1f%n", x);
        System.out.printf("In shadowedByLocalVariable: class variable x = %.1f%n", ScopeDemo.x);
    }
    
    public static void blockScoping() {
        do {
            double x = 1234.5;
            System.out.printf("In blockScoping, inside block: x = %.1f%n", x);
        } while (false);
        
        System.out.printf("In blockScoping, outside block: x = %.1f%n", x);
    }
    
    public static void main(String[] args) {
        shadowedByParameter(12.5);
        shadowedByLocalVariable();
        blockScoping();
    }
}

ScopeDemo.main(new String[0]);

In shadowedByParameter: parameter x = 12.5
In shadowedByLocalVariable: local varaible x = 2.5
In shadowedByLocalVariable: class variable x = 1.5
In blockScoping, inside block: x = 1234.5
In blockScoping, outside block: x = 1.5


ตัวอย่างนี้แสดงให้เห็นขอบเขตของ `x` ในบริบทต่าง ๆ กัน

`x` ที่เป็นตัวแปรชั้นนอกสุดประกาศเป็นตัวแปรของคลาส มีค่าเป็น 1.5 แต่ในเมทอด `shadowedByParameter` มีการประกาศพารามิเตอร์ `x` ซึ่งจะไปบดบัง `x` ที่เป็นตัวแปรของคลาส ทำให้เวลาที่แสดงค่าออกมาจะเป็นค่าของอาร์กิวเมนต์ที่ผ่านเข้ามาให้พารามิเตอร์ (12.5)

ในเมทอด `shadowedByLocalVariable` มีการประกาศตัวแปร `x` ภายในเมทอดโดยกำหนดให้มีค่าเท่ากับ 2.5 เมื่อแสดงค่าออกมาก็จะเป็นค่านี้เนื่องจาก `x` ตัวนี้ไปบดบัง `x` ที่เป็นตัวแปรของคลาสเช่นกัน แต่ในเมทอดนี้ยังมีการอ้างอิงถึง `x` ที่เป็นตัวแปรของคลาสด้วยโดยอ้างผ่านชื่อคลาสเป็น `ScopeDemo.x` ซึ่งนี่เป็นวิธีหนึ่งในการอ้างตัวแปรของคลาสที่ถูกบดบัง

ในเมทอด `blockScoping` มีการประกาศตัวแปร `x` ในคำสั่งแบบบล็อกที่เป็นส่วนหนึ่งของ `do` ... `while` ซึ่ง `x` ตัวนี้จะมีขอบเขตเฉพาะภายในบล็อกนี้เท่านั้น ดังนั้นเมื่อสั่งให้แสดงค่าของ `x` ภายในบล็อกจึงได้ค่า 1234.5 แต่เมื่อสั่งให้แสดงค่าของ `x` ภายนอกบล็อกจึงได้ค่า 1.5 เนื่องจากภายนอกบล็อกไม่มี `x` อื่นมาบดบัง `x` ที่เป็นตัวแปรของคลาสแล้วนั่นเอง